### PR TITLE
Add framerate display.

### PR DESCRIPTION
**Pull request by alliepiper**
Adds a vtkTextActor in the lower left corner that displays the average
FPS over the last 64 frames.

Adds a menu option to enable/disable the FPS display.

Adds a command line switch (-showfps) to turn on the FPS display.

### CODE REVIEW

**Comment by patrickoleary** [comment]
Vrui has a configuration flag to turn on framerate text information. It
might be nice to compare the results.

**Comment by alliepiper** [comment]
Nice, I didn't see that -- looks like WinKey + ScrollLock starts/stops the FPS monitor and removes framerate limiters.

 I tested it out a bit and it does match what my 'live' FPS display shows.

**Comment by patrickoleary** [comment]
Anactor might work better in the cave, so don't remove your implementation.
We could add it to the menu, and let it be placed whereever the end-user
needs it.

**Comment by alliepiper** [comment]
:+1:

**Pull request merged**
